### ISSUE TITLE
CaseIH 4400 Series Pack

### ISSUE THREAD

**Issue by Kieruss** [ABP-Modding/ABP-ISSUE-TRACKER#11]
- The side augers are not centred, and wobble a fair bit
- The main auger wobbles
- The main auger is missing part of the screw (found static in two headers)
- Additional Floaters found

![Floaters](https://user-images.githubusercontent.com/24835155/111055553-06aa8c80-84cb-11eb-9ffb-5e10f88b538a.png)

![Broken auger and floaters](https://user-images.githubusercontent.com/24835155/111055557-0b6f4080-84cb-11eb-9bcb-1001e5a3f47f.png)

[header4418_fixed.zip](https://github.com/ABP-Modding/ABP-ISSUE-TRACKER/files/6135977/header4418_fixed.zip)

**Comment by BenM9703** [comment]
FAO: @Adubmodding
